dma_comparison <- function(infile, dma_file){
  library(tidyverse)
  
  x <- readxl::read_excel(infile, sheet = "media_markets") %>%
    mutate(`Audience Rank` = row_number())
  
  
  ##Match to translation table
  name_translator <- tibble::tribble(
    ~nielsen_name,                       ~dma,
    "Abilene-Sweetwater, TX",          "Abilene-Sweetwater",
    "Albany-Schenectady-Troy, NY",     "Albany-Schenectady-Troy",
    "Albany, GA",                       "Albany, GA",
    "Albuquerque-Santa Fe, NM",        "Albuquerque-Santa Fe",
    "Alexandria, LA",              "Alexandria, LA",
    "Alpena, MI",                      "Alpena",
    "Amarillo, TX",                    "Amarillo",
    "Atlanta, GA",                     "Atlanta",
    "Augusta, GA",               "Augusta-Aiken",
    "Austin, TX",                      "Austin",
    "Bakersfield, CA",                 "Bakersfield",
    "Baltimore, MD",                   "Baltimore",
    "Bangor, ME",                      "Bangor",
    "Baton Rouge, LA",                 "Baton Rouge",
    "Beaumont-Port Arthur, TX",        "Beaumont-Port Arthur",
    "Bend, OR",                    "Bend, OR",
    "Billings, MT",                    "Billings",
    "Biloxi-Gulfport, MS",             "Biloxi-Gulfport",
    "Binghamton, NY",                  "Binghamton",
    "Birmingham (Anniston and Tuscaloosa), AL",   "Birmingham (Ann And Tusc)",
    "Bluefield-Beckley-Oak Hill, WV",  "Bluefield-Beckley-Oak Hill",
    "Boise, ID",                       "Boise",
    "Boston, MA (Manchester, NH)",         "Boston (Manchester)",
    "Bowling Green, KY",               "Bowling Green",
    "Buffalo, NY",                     "Buffalo",
    "Burlington, VT-Plattsburgh, NY",      "Burlington-Plattsburgh",
    "Butte-Bozeman, MT",               "Butte-Bozeman",
    "Casper-Riverton, WY",             "Casper-Riverton",
    "Cedar Rapids-Waterloo-Iowa City & Dubuque, IA",  "Cedar Rapids-Wtrlo-Iwc&Dub",
    "Champaign & Springfield-Decatur, IL",  "Champaign&Sprngfld-Decatur",
    "Charleston-Huntington, WV",       "Charleston-Huntington",
    "Charleston, SC",              "Charleston, SC",
    "Charlotte, NC",                   "Charlotte",
    "Charlottesville, VA",             "Charlottesville",
    "Chattanooga, TN",                 "Chattanooga",
    "Cheyenne, WY-Scottsbluff, NE",        "Cheyenne-Scottsbluff",
    "Chicago, IL",                     "Chicago",
    "Chico-Redding, CA",               "Chico-Redding",
    "Cincinnati, OH",                  "Cincinnati",
    "Clarksburg-Weston, WV",           "Clarksburg-Weston",
    "Cleveland-Akron (Canton), OH",    "Cleveland-Akron (Canton)",
    "Colorado Springs-Pueblo, CO",     "Colorado Springs-Pueblo",
    "Columbia-Jefferson City, MO",     "Columbia-Jefferson City",
    "Columbia, SC",                "Columbia, SC",
    "Columbus-Tupelo-West Point, MS",  "Columbus-Tupelo-W Pnt-Hstn",
    "Columbus, GA",  "Columbus, GA (Opelika, Al)",
    "Columbus, OH",                "Columbus, OH",
    "Corpus Christi, TX",              "Corpus Christi",
    "Dallas-Ft. Worth, TX",            "Dallas-Ft. Worth",
    "Davenport, IA-Rock Island-Moline, IL",   "Davenport-R.Island-Moline",
    "Dayton, OH",                      "Dayton",
    "Denver, CO",                      "Denver",
    "Des Moines-Ames, IA",             "Des Moines-Ames",
    "Detroit, MI",                     "Detroit",
    "Dothan, AL",                      "Dothan",
    "Duluth, MN-Superior, WI",             "Duluth-Superior",
    "El Paso, TX",        "El Paso (Las Cruces)",
    "Elmira, NY",            "Elmira (Corning)",
    "Erie, PA",                        "Erie",
    "Eugene, OR",                      "Eugene",
    "Eureka, CA",                      "Eureka",
    "Evansville, IN",                  "Evansville",
    "Fargo-Valley City, ND",           "Fargo-Valley City",
    "Flint-Saginaw-Bay City, MI",      "Flint-Saginaw-Bay City",
    "Fresno-Visalia, CA",              "Fresno-Visalia",
    "Ft. Myers-Naples, FL",            "Ft. Myers-Naples",
    "Ft. Smith-Fayetteville-Springdale-Rogers, AR",  "Ft. Smith-Fay-Sprngdl-Rgrs",
    "Ft. Wayne, IN",                   "Ft. Wayne",
    "Gainesville, FL",                 "Gainesville",
    "Glendive, MT",                    "Glendive",
    "Grand Junction-Montrose, CO",     "Grand Junction-Montrose",
    "Grand Rapids-Kalamazoo-Battle Creek, MI",  "Grand Rapids-Kalmzoo-B.Crk",
    "Great Falls, MT",                 "Great Falls",
    "Green Bay-Appleton, WI",          "Green Bay-Appleton",
    "Greensboro-High Point-Winston Salem, NC",  "Greensboro-H.Point-W.Salem",
    "Greenville-New Bern-Washington, NC",  "Greenville-N.Bern-Washngtn",
    "Greenville-Spartanburg, SC-Asheville, NC-Anderson,SC",  "Greenvll-Spart-Ashevll-And",
    "Greenwood-Greenville, MS",        "Greenwood-Greenville",
    "Harlingen-Weslaco-Brownsville-McAllen, TX",  "Harlingen-Wslco-Brnsvl-Mca",
    "Harrisburg-Lancaster-Lebanon-York, PA",  "Harrisburg-Lncstr-Leb-York",
    "Harrisonburg, VA",                "Harrisonburg",
    "Hartford & New Haven, CT",        "Hartford & New Haven",
    "Hattiesburg-Laurel, MS",          "Hattiesburg-Laurel",
    "Helena, MT",                      "Helena",
    "Houston, TX",                     "Houston",
    "Huntsville-Decatur (Florence), AL",   "Huntsville-Decatur (Flor)",
    "Idaho Falls-Pocatello, ID",  "Idaho Fals-Pocatllo(Jcksn)",
    "Indianapolis, IN",                "Indianapolis",
    "Jackson, MS",                 "Jackson, MS",
    "Jackson, TN",                 "Jackson, TB",
    "Jacksonville, FL",                "Jacksonville",
    "Johnstown-Altoona, PA",  "Johnstown-Altoona-St Colge",
    "Jonesboro, AR",                   "Jonesboro",
    "Joplin, MO-Pittsburg, KS",            "Joplin-Pittsburg",
    "Kansas City, MO",                 "Kansas City",
    "Knoxville, TN",                   "Knoxville",
    "La Crosse-Eau Claire, WI",        "La Crosse-Eau Claire",
    "Lafayette, IN",               "Lafayette, IN",
    "Lafayette, LA",               "Lafayette, LA",
    "Lake Charles, LA",                "Lake Charles",
    "Lansing, MI",                     "Lansing",
    "Laredo, TX",                      "Laredo",
    "Las Vegas, NV",                   "Las Vegas",
    "Lexington, KY",                   "Lexington",
    "Lima, OH",                        "Lima",
    "Lincoln & Hastings-Kearney, NE",     "Lincoln & Hastings-Krny",
    "Little Rock-Pine Bluff, AR",      "Little Rock-Pine Bluff",
    "Los Angeles, CA",                 "Los Angeles",
    "Louisville, KY",                  "Louisville",
    "Lubbock, TX",                     "Lubbock",
    "Macon, GA",                       "Macon",
    "Madison, WI",                     "Madison",
    "Mankato, MN",                     "Mankato",
    "Marquette, MI",                   "Marquette",
    "Medford-Klamath Falls, OR",       "Medford-Klamath Falls",
    "Memphis, TN",                     "Memphis",
    "Meridian, MS",                    "Meridian",
    "Miami-Fort Lauderdale, FL",        "Miami-Ft. Lauderdale",
    "Milwaukee, WI",                   "Milwaukee",
    "Minneapolis-St. Paul, MN",        "Minneapolis-St. Paul",
    "Minot-Bismarck-Dickinson(Williston), ND",  "Minot-Bsmrck-Dcknsn(Wlstn)",
    "Missoula, MT",                    "Missoula",
    "Mobile, AL-Pensacola (Ft. Walton Beach), FL",  "Mobile-Pensacola (Ft Walt)",
    "Monroe, LA-El Dorado, AR",            "Monroe-El Dorado",
    "Monterey-Salinas, CA",            "Monterey-Salinas",
    "Montgomery-Selma, AL",            "Montgomery-Selma",
    "Myrtle Beach-Florence, SC",       "Myrtle Beach-Florence",
    "Nashville, TN",                   "Nashville",
    "New Orleans, LA",                 "New Orleans",
    "New York, NY",                    "New York",
    "Norfolk-Portsmouth-Newport News, VA",  "Norfolk-Portsmth-Newpt Nws",
    "North Platte, NE",                "North Platte",
    "Odessa-Midland, TX",              "Odessa-Midland",
    "Oklahoma City, OK",               "Oklahoma City",
    "Omaha, NE",                       "Omaha",
    "Orlando-Daytona Beach-Melbourne, FL",  "Orlando-Daytona Bch-Melbrn",
    "Ottumwa, IA-Kirksville, MO",          "Ottumwa-Kirksville",
    "Paducah, KY-Cape Girardeau, MO-Harrisburg, IL",  "Paducah-Cape Girard-Harsbg",
    "Palm Springs, CA",                "Palm Springs",
    "Panama City, FL",                 "Panama City",
    "Parkersburg, WV",                 "Parkersburg",
    "Peoria-Bloomington, IL",          "Peoria-Bloomington",
    "Philadelphia, PA",                "Philadelphia",
    "Phoenix, AZ",          "Phoenix (Prescott)",
    "Pittsburgh, PA",                  "Pittsburgh",
    "Portland-Auburn, ME",             "Portland-Auburn",
    "Portland, OR",                "Portland, OR",
    "Presque Isle, ME",                "Presque Isle",
    "Providence, RI-New Bedford, MA",      "Providence-New Bedford",
    "Quincy, IL-Hannibal, MO-Keokuk, IA",      "Quincy-Hannibal-Keokuk",
    "Raleigh-Durham (Fayetteville), NC",  "Raleigh-Durham (Fayetvlle)",
    "Rapid City, SD",                  "Rapid City",
    "Reno, NV",                        "Reno",
    "Richmond-Petersburg, VA",         "Richmond-Petersburg",
    "Roanoke-Lynchburg, VA",           "Roanoke-Lynchburg",
    "Rochester, MN-Mason City, IA-Austin, MN", "Rochester-Mason City-Austin",
    "Rochester, NY",               "Rochester, NY",
    "Rockford, IL",                    "Rockford",
    "Sacramento-Stockton-Modesto, CA",    "Sacramnto-Stkton-Modesto",
    "Salisbury, MD",                   "Salisbury",
    "Salt Lake City, UT",              "Salt Lake City",
    "San Angelo, TX",                  "San Angelo",
    "San Antonio, TX",                 "San Antonio",
    "San Diego, CA",                   "San Diego",
    "San Francisco-Oakland-San Jose, CA",  "San Francisco-Oak-San Jose",
    "Santa Barbara-Santa Maria-San Luis Obispo, CA",  "Santabarbra-Sanmar-Sanluob",
    "Savannah, GA",                    "Savannah",
    "Seattle-Tacoma, WA",              "Seattle-Tacoma",
    "Sherman, TX-Ada, OK",                 "Sherman-Ada",
    "Shreveport, LA",                  "Shreveport",
    "Sioux City, IA",                  "Sioux City",
    "Sioux Falls (Mitchell), SD",       "Sioux Falls(Mitchell)",
    "South Bend-Elkhart, IN",          "South Bend-Elkhart",
    "Spokane, WA",                     "Spokane",
    "Springfield-Holyoke, MA",         "Springfield-Holyoke",
    "Springfield, MO",             "Springfield, MO",
    "St. Joseph, MO",                  "St. Joseph",
    "St. Louis, MO",                   "St. Louis",
    "Syracuse, NY",                    "Syracuse",
    "Tallahassee, FL-Thomasville, GA",     "Tallahassee-Thomasville",
    "Tampa-St. Petersburg (Sarasota), FL",   "Tampa-St. Pete (Sarasota)",
    "Terre Haute, IN",                 "Terre Haute",
    "Toledo, OH",                      "Toledo",
    "Topeka, KS",                      "Topeka",
    "Traverse City-Cadillac, MI",      "Traverse City-Cadillac",
    "Tri-Cities, TN-VA",           "Tri-Cities, TN-VA",
    "Tucson (Sierra Vista), AZ",       "Tucson (Sierra Vista)",
    "Tulsa, OK",                       "Tulsa",
    "Twin Falls, ID",                  "Twin Falls",
    "Tyler-Longview(Lufkin & Nacogdoches), TX",   "Tyler-Longview(Lfkn&Ncgd)",
    "Utica, NY",                       "Utica",
    "Victoria, TX",                    "Victoria",
    "Waco-Temple-Bryan, TX",           "Waco-Temple-Bryan",
    "Washington, DC (Hagerstown, MD)",   "Washington, DC (Hagrstwn)",
    "Watertown, NY",                   "Watertown",
    "Wausau-Rhinelander, WI",          "Wausau-Rhinelander",
    "West Palm Beach-Ft. Pierce, FL",  "West Palm Beach-Ft. Pierce",
    "Wheeling, WV-Steubenville, OH",       "Wheeling-Steubenville",
    "Wichita Falls, TX-Lawton, OK",      "Wichita Falls & Lawton",
    "Wichita-Hutchinson, KS Plus",    "Wichita-Hutchinson Plus",
    "Wilkes Barre-Scranton, PA", "Wilkes Barre-Scranton-Hztn",
    "Wilmington, NC",                 "Wilmington",
    "Yakima-Pasco-Richland-Kennewick, WA", "Yakima-Pasco-Rchlnd-Knnwck",
    "Youngstown, OH",                 "Youngstown",
    "Yuma, AZ-El Centro, CA",         "Yuma-El Centro",
    "Zanesville, OH",                 "Zanesville"
  )
  
  x <- x %>% inner_join(name_translator) %>%
    dplyr::select(nielsen_name,count, `Audience Rank`) %>%
    dplyr::rename(DMA = nielsen_name)
  
  ##Add population rank
  pop_rank <- tibble::tribble(
    ~DMA, ~`Population Rank`,
    "New York, NY",               1,
    "Los Angeles, CA",               2,
    "Chicago, IL",               3,
    "Philadelphia, PA",               4,
    "San Francisco-Oakland-San Jose, CA",               5,
    "Dallas-Ft. Worth, TX",               6,
    "Washington, DC (Hagerstown, MD)",               7,
    "Houston, TX",               8,
    "Atlanta, GA",               9,
    "Boston, MA (Manchester, NH)",              10,
    "Phoenix, AZ",              11,
    "Seattle-Tacoma, WA",              12,
    "Detroit, MI",              13,
    "Tampa-St. Petersburg (Sarasota), FL",              14,
    "Miami-Fort Lauderdale, FL",              15,
    "Minneapolis-St. Paul, MN",              16,
    "Denver, CO",              17,
    "Sacramento-Stockton-Modesto, CA",              18,
    "Orlando-Daytona Beach-Melbourne, FL",              19,
    "Cleveland-Akron (Canton), OH",              20,
    "Portland, OR",              21,
    "San Diego, CA",              22,
    "St. Louis, MO",              23,
    "Charlotte, NC",              24,
    "Raleigh-Durham (Fayetteville), NC",              25,
    "Baltimore, MD",              26,
    "Indianapolis, IN",              27,
    "Salt Lake City, UT",              28,
    "Pittsburgh, PA",              29,
    "Nashville, TN",              30,
    "Hartford & New Haven, CT",              31,
    "San Antonio, TX",              32,
    "Columbus, OH",              33,
    "Kansas City, MO",              34,
    "Cincinnati, OH",              35,
    "Milwaukee, WI",              36,
    "Greenville-Spartanburg, SC-Asheville, NC-Anderson,SC",              37,
    "Las Vegas, NV",              38,
    "Austin, TX",              39,
    "West Palm Beach-Ft. Pierce, FL",              40,
    "Grand Rapids-Kalamazoo-Battle Creek, MI",              41,
    "Harrisburg-Lancaster-Lebanon-York, PA",              42,
    "Norfolk-Portsmouth-Newport News, VA",              43,
    "Fresno-Visalia, CA",              44,
    "Birmingham (Anniston and Tuscaloosa), AL",              45,
    "Albuquerque-Santa Fe, NM",              46,
    "Oklahoma City, OK",              47,
    "Jacksonville, FL",              48,
    "Greensboro-High Point-Winston Salem, NC",              49,
    "Memphis, TN",              50,
    "Louisville, KY",              51,
    "New Orleans, LA",              52,
    "Providence, RI-New Bedford, MA",              53,
    "Buffalo, NY",              54,
    "Wilkes Barre-Scranton, PA",              55,
    "Richmond-Petersburg, VA",              56,
    "Little Rock-Pine Bluff, AR",              57,
    "Mobile, AL-Pensacola (Ft. Walton Beach), FL",              58,
    "Albany-Schenectady-Troy, NY",              59,
    "Tulsa, OK",              60,
    "Knoxville, TN",              61,
    "Ft. Myers-Naples, FL",              62,
    "Lexington, KY",              63,
    "Harlingen-Weslaco-Brownsville-McAllen, TX",              64,
    "Dayton, OH",              65,
    "Wichita-Hutchinson, KS Plus",              66,
    "Tucson (Sierra Vista), AZ",              67,
    "Roanoke-Lynchburg, VA",              68,
    "Spokane, WA",              69,
    "Flint-Saginaw-Bay City, MI",              70,
    "Charleston-Huntington, WV",              71,
    "Des Moines-Ames, IA",              72,
    "Green Bay-Appleton, WI",              73,
    "Omaha, NE",              74,
    "Rochester, NY",              75,
    "Columbia, SC",              76,
    "Springfield, MO",              77,
    "Toledo, OH",              78,
    "Huntsville-Decatur (Florence), AL",              79,
    "Syracuse, NY",              80,
    "Portland-Auburn, ME",              81,
    "El Paso, TX",              82,
    "Waco-Temple-Bryan, TX",              83,
    "Madison, WI",              84,
    "Shreveport, LA",              85,
    "Paducah, KY-Cape Girardeau, MO-Harrisburg, IL",              86,
    "Champaign & Springfield-Decatur, IL",              87,
    "Chattanooga, TN",              88,
    "Colorado Springs-Pueblo, CO",              89,
    "Savannah, GA",              90,
    "Baton Rouge, LA",              91,
    "Cedar Rapids-Waterloo-Iowa City & Dubuque, IA",              92,
    "Jackson, MS",              93,
    "South Bend-Elkhart, IN",              94,
    "Burlington, VT-Plattsburgh, NY",              95,
    "Charleston, SC",              96,
    "Ft. Smith-Fayetteville-Springdale-Rogers, AR",              97,
    "Greenville-New Bern-Washington, NC",              98,
    "Tri-Cities, TN-VA",              99,
    "Myrtle Beach-Florence, SC",             100,
    "Johnstown-Altoona, PA",             101,
    "Davenport, IA-Rock Island-Moline, IL",             102,
    "Boise, ID",             103,
    "Tallahassee, FL-Thomasville, GA",             104,
    "Monterey-Salinas, CA",             105,
    "Bakersfield, CA",             106,
    "Reno, NV",             107,
    "Tyler-Longview(Lufkin & Nacogdoches), TX",             108,
    "Evansville, IN",             109,
    "Santa Barbara-Santa Maria-San Luis Obispo, CA",             110,
    "Lincoln & Hastings-Kearney, NE",             111,
    "Springfield-Holyoke, MA",             112,
    "Ft. Wayne, IN",             113,
    "Augusta, GA",             114,
    "Yakima-Pasco-Richland-Kennewick, WA",             115,
    "Sioux Falls (Mitchell), SD",             116,
    "Lansing, MI",             117,
    "Youngstown, OH",             118,
    "Macon, GA",             119,
    "Peoria-Bloomington, IL",             120,
    "Eugene, OR",             121,
    "Fargo-Valley City, ND",             122,
    "Traverse City-Cadillac, MI",             123,
    "Montgomery-Selma, AL",             124,
    "Lafayette, LA",             125,
    "Corpus Christi, TX",             126,
    "Columbus, GA",             127,
    "La Crosse-Eau Claire, WI",             128,
    "Amarillo, TX",             129,
    "Chico-Redding, CA",             130,
    "Wilmington, NC",             131,
    "Columbus-Tupelo-West Point, MS",             132,
    "Columbia-Jefferson City, MO",             133,
    "Rockford, IL",             134,
    "Monroe, LA-El Dorado, AR",             135,
    "Topeka, KS",             136,
    "Beaumont-Port Arthur, TX",             137,
    "Wausau-Rhinelander, WI",             138,
    "Palm Springs, CA",             139,
    "Lubbock, TX",             140,
    "Odessa-Midland, TX",             141,
    "Medford-Klamath Falls, OR",             142,
    "Salisbury, MD",             143,
    "Duluth, MN-Superior, WI",             144,
    "Wichita Falls, TX-Lawton, OK",             145,
    "Minot-Bismarck-Dickinson(Williston), ND",             146,
    "Erie, PA",             147,
    "Albany, GA",             148,
    "Sioux City, IA",             149,
    "Panama City, FL",             150,
    "Joplin, MO-Pittsburg, KS",             151,
    "Terre Haute, IN",             152,
    "Yuma, AZ-El Centro, CA",             153,
    "Rochester, MN-Mason City, IA-Austin, MN",             154,
    "Idaho Falls-Pocatello, ID",             155,
    "Bangor, ME",             156,
    "Biloxi-Gulfport, MS",             157,
    "Binghamton, NY",             158,
    "Wheeling, WV-Steubenville, OH",             159,
    "Gainesville, FL",             160,
    "Sherman, TX-Ada, OK",             161,
    "Bluefield-Beckley-Oak Hill, WV",             162,
    "Abilene-Sweetwater, TX",             163,
    "Missoula, MT",             164,
    "Hattiesburg-Laurel, MS",             165,
    "Billings, MT",             166,
    "Utica, NY",             167,
    "Clarksburg-Weston, WV",             168,
    "Quincy, IL-Hannibal, MO-Keokuk, IA",             169,
    "Harrisonburg, VA",             170,
    "Lake Charles, LA",             171,
    "Laredo, TX",             172,
    "Rapid City, SD",             173,
    "Dothan, AL",             174,
    "Watertown, NY",             175,
    "Elmira, NY",             176,
    "Jackson, TN",             177,
    "Alexandria, LA",             178,
    "Marquette, MI",             179,
    "Bowling Green, KY",             180,
    "Charlottesville, VA",             181,
    "Jonesboro, AR",             182,
    "Lafayette, IN",             183,
    "Grand Junction-Montrose, CO",             184,
    "Butte-Bozeman, MT",             185,
    "Lima, OH",             186,
    "Twin Falls, ID",             187,
    "Greenwood-Greenville, MS",             188,
    "Meridian, MS",             189,
    "Bend, OR",             190,
    "Great Falls, MT",             191,
    "Eureka, CA",             192,
    "Parkersburg, WV",             193,
    "San Angelo, TX",             194,
    "Casper-Riverton, WY",             195,
    "Cheyenne, WY-Scottsbluff, NE",             196,
    "St. Joseph, MO",             197,
    "Ottumwa, IA-Kirksville, MO",             198,
    "Mankato, MN",             199,
    "Victoria, TX",             200,
    "Zanesville, OH",             201,
    "Helena, MT",             202,
    "Presque Isle, ME",             203,
    "Alpena, MI",             204,
    "North Platte, NE",             205,
    "Glendive, MT",             206
  )
  
  x %>% inner_join(pop_rank) %>%
    mutate(Comparison = ifelse(`Audience Rank` == `Population Rank`, "Same",
                                   ifelse(`Audience Rank` < `Population Rank`,"Higher", "Lower"))) %>%
    dplyr::rename(`Total Audience` = count) %>%
    readr::write_csv(paste0(dma_file, ".csv"))
  
}